[pytest]
pythonpath = src packages/pantaray-llm/src .
testpaths = tests
python_files = test_*.py
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function 
addopts = --import-mode=importlib
filterwarnings =
    ignore:'enablePackrat' deprecated - use 'enable_packrat':DeprecationWarning:pyiceberg\.expressions\.parser
    ignore:'escChar' argument is deprecated, use 'esc_char':DeprecationWarning:pyiceberg\.expressions\.parser
    ignore:'unquoteResults' argument is deprecated, use 'unquote_results':DeprecationWarning:pyiceberg\.expressions\.parser
    ignore:Using `@model_validator` with mode='after' on a classmethod is deprecated\..*:pydantic.warnings.PydanticDeprecatedSince212:pyiceberg\.table\.metadata
