from __future__ import annotations

LLM_TRANSPORT_MAX_ATTEMPTS = 5
LLM_TOOL_CALL_MAX_CONSECUTIVE_ERRORS = 5
PROVIDER_SDK_MAX_ATTEMPTS = 1
OPENAI_SDK_MAX_RETRIES = PROVIDER_SDK_MAX_ATTEMPTS - 1

__all__ = [
    "LLM_TOOL_CALL_MAX_CONSECUTIVE_ERRORS",
    "LLM_TRANSPORT_MAX_ATTEMPTS",
    "OPENAI_SDK_MAX_RETRIES",
    "PROVIDER_SDK_MAX_ATTEMPTS",
]
